### ISSUE TITLE
Something missing?

### ISSUE THREAD

**Issue by chadbrewbaker** [bodil/purescript-test-unit#1]
OS X10.10, fresh pulp from npm, and fresh purescript from cabal-1.18.1.4 under ghc-7.8.3.

I got the following error:
pulp test

* Building project in /Users/crb002/github/purescript-test-unit

Error at src/Test/Unit.purs line 20, column 1: 

Error in module Test.Unit

Cannot import unknown module 'Control.Monad.Cont.Trans'

* ERROR: Subcommand terminated with error code 1

**Comment by hdgarrood** [comment]
This is most probably due to not running `bower install` first - `pulp test` won't do that for you.

**Comment by bodil** [comment]
It's no longer even using `ContT` in any case, so I'm going to assume this has been fixed now. :)
