### ISSUE TITLE
JUnit xml support

### ISSUE THREAD

**Issue by rahulsom** [bodil/purescript-test-unit#12]
Is there a way the results of the unit tests can be hooked into a CI system like Jenkins?

**Comment by bodil** [comment]
The quick answer is no. I'd like to add support for pluggable output handlers at some point, but I'm not sure how. I wonder if it wouldn't be sufficient to just add [TAP](https://testanything.org/) output as a built-in option, and leave it to the consumer to pipe it through a converter to the desired format.
