### ISSUE TITLE
Test output formatting

### ISSUE THREAD

**Issue by spicydonuts** [bodil/purescript-test-unit#13]
It looks like the test output is supposed to rewrite lines to replace "pending" messages with "success/failure" messages, but that doesn't seem to be working.  I'm not sure if this is a problem with my console (I tried on OSX with both bash and zsh, and in both Terminal.app and iTerm) or the output itself.  Here are some samples (bash vs zsh made no difference, so this is just Terminal.app vs iTerm):

Terminal.app
```
→ Running: Autocomplete→ Running: Send/Subscribe→ Running: Integration Test✓ Passed: Integration Test
✓ Passed: Send/Subscribe
✓ Passed: Autocomplete
→ Running: Util.Signal→ Running: whenEqual✓ Passed: whenEqual
→ Running: whenChangeTo✓ Passed: whenChangeTo
→ Running: since✓ Passed: since
→ Running: debounce✓ Passed: debounce
✓ Passed: Util.Signal
```

iTerm
```
→ Running: Autocomplete→ Running: Send/Subscribe✓ Passed: Autocomplete
→ Running: Util.Signal✓ Passed: whenEqual
✓ Passed: whenChangeTo
✓ Passed: since
✓ Passed: Util.Signal
```

iTerm seems better, but it doesn't work well with nested tests.  Terminal.app doesn't seem to clear lines at all.

**Comment by spicydonuts** [comment]
Oops, forgot to include the test structure:
```
main = runTest do
  test "Autocomplete" do
    test "Send/Subscribe" do
      test "Integration Test" do
        ...

  test "Util.Signal" do
    test "whenEqual" do
      ...
    test "whenChangeTo" do
      ...
    test "since" do
      ...
    test "debounce" do
      ...
```

**Comment by tfausak** [comment]
👍 The test output looks pretty weird.

**Comment by bodil** [comment]
Looks like two problems:

* Nested tests aren't formatted correctly (a bug in test-unit - I think I've honestly never used them, so I've never noticed).
* Apple's Terminal.app looks like it's got poor support for the ANSI terminal control codes in use. I wonder if the fix for that is to simplify the output for dumb terminals (which would also make it work in an Emacs buffer, a problem I've been experiencing myself).

**Comment by rgrempel** [comment]
A workaround I've used that makes things look nicer is to add newlines to the outer-level names ... something like this:

```purescript
main = runTest do
  test "Autocomplete\n" do
    test "Send/Subscribe" do
      test "Integration Test" do
        ...

  test "Util.Signal\n" do
    test "whenEqual" do
      ...
    test "whenChangeTo" do
      ...
    test "since" do
      ...
    test "debounce" do
      ...

**Comment by bodil** [comment]
I've improved the output of nested tests, though I'm not pleased with it - I can't see any way of detecting whether a test is inside another test without complicating the test syntax, so test output will give no indication of nesting, but at least it isn't glitchy anymore.

It should now also revert to simpler output on less capable terminals. It works in Emacs eshell, but I've no way of testing it in Terminal.app.
