### ISSUE TITLE
type mismatch - adding 6.0.0 prevents project from compiling

### ISSUE THREAD

**Issue by bagl** [bodil/purescript-test-unit#15]
While working on purescript-intmaps, we've found out that just adding v6.0.0 as a dependency prevents the project from compiling with the following type mismatch error:

```
Error found:
in module Test.Unit.Output.Simple
at /home/petr/devel/purescript-intmaps/bower_components/purescript-test-unit/src/Test/Unit/Output/Simple.purs line 49, column 10 - line 52, column 5

  Could not match type

    Unit

  with type

    String

while trying to match type Aff
                             ( console :: CONSOLE
                             | _2
                             )
                             _3
  with type Aff
              ( console :: CONSOLE
              | _0
              )
              String
while checking that expression (bind (log "1 test failed:\n")) (\__unused ->
                                                                  list errors
                                                               )
  has type Aff
             ( console :: CONSOLE
             | _0
             )
             _1
in value declaration printErrors
```

Compiling the `purescript-test-unit` on its own is without problem. I have no idea what is happening...

**Comment by bodil** [comment]
I've no idea either, but I had a go at trying to reproduce it, and it compiles without incident using psc 0.8.5. Here's a diff of the changes I made to purescript-intmaps HEAD, for reference - nothing more than updating the tests to 6.0.0 syntax: [diff.txt](https://github.com/bodil/purescript-test-unit/files/265250/diff.txt)
