### ISSUE TITLE
readme on pursuit

### ISSUE THREAD

**Issue by AljoschaMeyer** [bodil/purescript-test-unit#16]
The readme on pursuit shows incorrect imports in the example:

```purescript
import Test.Unit (test, runTest)
```
instead of
```purescript
import Test.Unit (test)
import Test.Unit.Main (runTest)
```

The readme in this repo gives the correct imports. I don't know anything about pursuit, but can this be corrected?

Also an unrelated, big "thank you" for the high-level usage documentation that comes with your modules. As a newbie to purscript and fp, those are invaluable.

**Comment by bodil** [comment]
I think this is probably because when I released the latest version, Pursuit and psc-publish weren't in sync so I couldn't push the updated docs. I'll retry.

**Comment by bodil** [comment]
Looks good now: https://pursuit.purescript.org/packages/purescript-test-unit/6.0.1
