### ISSUE TITLE
Combining with quickcheck

### ISSUE THREAD

**Issue by MichaelXavier** [bodil/purescript-test-unit#2]
This may not be an issue or just a documentation issue but I got bitten by it today and found it kind of surprising. runTest will exit the process when it finishes. I've got some tests I want to do in test unit and others in quickcheck. If you do something like this:

```purescript
main = do
  runTest $ do
    mod1Unit
    mod2Unit
  qcTests
```

qcTests will never run and everything will look green. Instead you'd want qcTests to run first. As I said, not sure what the right thing is here. One solution I can see is to offer a runTest that returns a Boolean or something so you could do

```purescript
main = do
  ok <- runTest $ sometests
  -- ...
  if ok then exitSuccess else exitFailure
```

Where exitSuccess can be its own package. You'd also want a similar feature from quickCheck which should be pretty easy.

**Comment by hdgarrood** [comment]
Maybe we could address this without even having to break the public API by using [onBeforeExit](http://pursuit.purescript.org/packages/purescript-node-process/0.2.0/docs/Node.Process#v:onBeforeExit) - if the tests fail, we install an onBeforeExit handler to make sure it exits with 1?

**Comment by bodil** [comment]
The event loop won't go idle at all if there are listening sockets open etc, hence the explicit `process.exit`. However, nowadays you can just run tests using `runAff` and handle this on your own if necessary, and I just added a QuickCheck layer, which gives you less reason to even need to do so.
