### ISSUE TITLE
Support for `purescript-strongcheck`

### ISSUE THREAD

**Issue by menelaos** [bodil/purescript-test-unit#20]
Have you considered adding support for [`purescript-strongcheck`](https://github.com/purescript-contrib/purescript-strongcheck) in `purescript-test-unit`?

**Comment by bodil** [comment]
I'm a bit wary of adding more dependencies to the core library - really, the Quickcheck support should probably have been in a package of its own. That's definitely the way I'd prefer to add Strongcheck support, or anything else.
