### ISSUE TITLE
Proposal to add BDD syntax

### ISSUE THREAD

**Issue by Risto-Stevcev** [bodil/purescript-test-unit#22]
So it would look like this:

```purescript
main = runTest do
  describe "readTextFile" do
    it "should read the contents of the file" do
      fileContents <- FS.readTextFile UTF8 "file.txt"
      fileContents `shouldEqual` "hello here are your file contents"
```

I like BDD because the test descriptions are less awkward and it's a little easier to read. I think it should be easy to do since it would just be synonyms to already existing functions:

`suite` -> `describe`
`test` -> `it`
`Assert.equal` -> `shouldEqual`

**Comment by bodil** [comment]
As long as it doesn't change the semantics at all, I'd be happy to include it.
