### ISSUE TITLE
Is this library compatible with the DOM?

### ISSUE THREAD

**Issue by AKST** [bodil/purescript-test-unit#4]
First off I'm not using this library via `pulp`.

After spending hours to get this library to actually type check, I ran it in `phantomjs`, then next minute I get this in the shell.

```
ReferenceError: Can't find variable: process
    /.../public/scripts/tests.js:33016 in savePos
    /.../public/scripts/tests.js:38693 in __do
    /.../public/scripts/tests.js:52954 in __do
    /.../public/scripts/tests.js:54470 in __do
    /.../public/scripts/tests.js:54478
```

Looks like I need to run this in node, so I just ran `/.../public/scripts/tests.js` in `node`, of course that doesn't actually work because there's no DOM in node. I know could probably include [`domjs`](https://github.com/tmpvar/jsdom) so it will run the code in node, but that's hardly an ideal solution and the lack of the DOM is probably just the tip of the iceburg. 

To be thorough this was the exact issue I was getting, which would happen from a missing DOM.

```
/.../public/scripts/tests.js:894
  var div = document.createElement("div");
  
TypeError: Cannot call method 'createElement' of undefined
  ...
```

Anyways, am I doing something stupid? or does this not work with the DOM?

**Comment by puffnfresh** [comment]
It is not compatible. We should fix that. How should test results be reported?

**Comment by puffnfresh** [comment]
Or maybe we should find a way to be pure (e.g. use virtual-dom) instead of allowing impure tests.

**Comment by bodil** [comment]
As of 1.1.6 it should run without error in both PhantomJS and the browser, although I haven't tested it against the most recent versions of the compiler. Also, the whole point of this library is to test effectful functions—if all your code is pure, you're probably much better off using QuickCheck?

**Comment by bodil** [comment]
...although I just noticed the 1.1.6 tag is missing on the Github side. That'll explain it. :)

**Comment by bodil** [comment]
Sorted now. Please let me know if 1.1.6 is exhibiting the same issues.

**Comment by AKST** [comment]
Thanks! Will check some time tomorrow (2:00am over here)

**Comment by AKST** [comment]
Thanks, looks like it works now!
